// import image
import blogImg from "../../assets/images/blog.png";

export const BlogData = [
  {
    id: 1,
    date: "13",
    month: "October",
    year: "2020",
    link: "/",
    title: "How to learn React",
    author: "Bablu Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
    domain: "Web Dev",
  },
  {
    id: 2,
    date: "10",
    month: "October",
    year: "2020",
    readMore: "/",
    title: "How to learn React",
    author: "Bablu Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
    domain: "App Dev",
  },
  {
    id: 3,
    date: "17",
    month: "September",
    year: "2020",
    readMore: "/",
    title: "How to learn React",
    author: "Bablu Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
    domain: "Machine Learning",
  },
  {
    id: 4,
    date: "13",
    month: "September",
    year: "2020",
    readMore: "/",
    title: "How to learn React",
    author: "Bablu Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
    domain: "Designing",
  },
  {
    id: 5,
    date: "9",
    month: "September",
    year: "2020",
    readMore: "/",
    title: "How to learn Angular",
    author: "Shyam Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
    domain: "Managerial",
  },
  {
    id: 6,
    date: "9",
    month: "September",
    year: "2020",
    readMore: "/",
    title: "How to learn Angular",
    author: "Shyam Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
    domain: "Web Dev",
  },
  {
    id: 7,
    date: "9",
    month: "September",
    year: "2020",
    readMore: "/",
    title: "How to learn Angular",
    author: "Shyam Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
    domain: "Web Dev",
  },
  {
    id: 8,
    date: "9",
    month: "September",
    year: "2020",
    readMore: "/",
    title: "How to learn Angular",
    author: "Shyam Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
    domain: "Web Dev",
  },
  {
    id: 9,
    date: "9",
    month: "September",
    year: "2020",
    readMore: "/",
    title: "How to learn Angular",
    author: "Shyam Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
    domain: "Web Dev",
  },
  {
    id: 10,
    date: "9",
    month: "September",
    year: "2020",
    readMore: "/",
    title: "How to learn Angular",
    author: "Shyam Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
  },
  {
    id: 11,
    date: "9",
    month: "September",
    year: "2020",
    readMore: "/",
    title: "How to learn Angular",
    author: "Shyam Dev",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium debitis praesentium sint nemo quia incidunt aliquam nulla quisquam delectus odio omnis, doloribus suscipit architecto magni inventore odit repellat? Eum, non.",
    image: blogImg,
  },
];
